service: github-webhook

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    GITHUB_WEBHOOK_SECRET: ${ssm:githubWebhookSecret}
    GITHUB_USER_TOKEN: ${ssm:githubUserToken}
    CHANNEL_ACECSS_TOKEN: ${ssm:channelAccessToken}
    CHANNEL_ACECSS_SECRET: ${ssm:channelAccessSecret}

functions:
  prAutoAssign:
    handler: prAutoAssign/handler.prAutoAssign
    events:
      - http:
          path: prAutoAssign
          method: post
          cors: true

  reviewRequiredNoti:
    handler: reviewRequiredNoti/handler.reviewRequiredNoti
    events:
      - http:
          path: reviewRequiredNoti
          method: post
          cors: true

  prAssignNoti:
    handler: prAssignNoti/handler.prAssignNoti
    events:
      - http:
          path: prAssignNoti
          method: post
          cors: true

plugins:
  - serverless-offline