service: ch-desk-web

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    GITHUB_WEBHOOK_SECRET: ${ssm:githubWebhookSecret}
    GITHUB_USER_TOKEN: ${ssm:githubUserToken}

functions:
  pr_auto_assign:
    handler: autoAssign/handler.pr_auto_assign
    events:
      - http:
          path: pr_auto_assign
          method: post
          cors: true

plugins:
  - serverless-offline